apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 800373800709.dkr.ecr.us-east-1.amazonaws.com/testsah:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This should match the labels of your Deployment
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 80
  type: LoadBalancer 
